#%RAML 1.0
title: transportap-system-FastGo
description: "This is an Transport application"
resourceTypes:
  routeData: !include api/routeresourceType.raml
  schuduleData: !include api/schuduleresourceType.raml
/{transportType}:
   /{transportCompany}:
      /routes:
        type:
          routeData
      /schudules:
         type:
          schuduleData

